project-key: MIN

name: minerva

parameters:
  data_dir: /mnt/ml-team/minerva/resources/whales/data
  solution_dir: resources/whales/solution/classification

  # data_dir: path/to/your/data # for instance resources/whales/data
  # solution_dir:  path/to/your/solution # for instance resources/whales/solution/localization

exclude:
  - resources
  - output
  - neptune.log
  - offline_job.log
  - .idea
  - .git
